### ISSUE TITLE
How do I use the active environment in Io?

### ISSUE THREAD

**Issue by halloleo** [AlesTsurko/eerie#36]
I have done the following:

    $ eerie  env:activate default

    $ eerie install https://github.com/AlesTsurko/Markdown.git
    -> Install Markdown
    - Fetching Markdown
    ...
    $ io
    Io 20170906
    Io> "# Hello" markdownToHTML 

And I get:

    Exception: Sequence does not respond to 'markdownToHTML'
    ---------
    Sequence markdownToHTML              Command Line 1

Somehow the io executable doesn't seem to use the active env. How can I tell io to use it?

**Comment by ales-tsurko** [comment]
You need to bring the addon context first, to be able to use this method. In other words, you need to import it. Just call `Markdown`.

Also, you don't need to install Markdown as Eerie depends on it and if you installed Eerie, you already have Markdown.

If you didn't create other environments, there's no need to activate the default environment as this is already the current environment.

And the method `markdownToHTML` was renamed to `markdownToHtml`.

**Comment by halloleo** [comment]
I finally got it working! In the Io repl I have to run

    Io> Markdown toHtml("# Hello")

Thanks @ales-tsurko for your patience!
