### ISSUE TITLE
Garbage on installation failure

### ISSUE THREAD

**Issue by ales-tsurko** [AlesTsurko/eerie#8]
If a package installation was failed, Eerie keeps a directory for this package and because of this doesn't allow to reinstall the package. 

It also looks like there is a recording in `config.json`, because the manual removing doesn't fix the problem.

**Comment by ales-tsurko** [comment]
Related to #7

**Comment by ekozhura** [comment]
And the most frustrating thing - transaction lock :)

**Comment by ales-tsurko** [comment]
@ekozhura added a ticket for this: https://github.com/AlesTsurko/eerie/issues/13

**Comment by ales-tsurko** [comment]
Issue noted here, that relates `config.json`, possibly fixed in https://github.com/AlesTsurko/eerie/commit/a6f3744b18a4050bbf2c5843d4a6e59cf65752fe

**Comment by ales-tsurko** [comment]
No longer relevant.
